// Code generated by go tool dist; DO NOT EDIT.

package main

const defaultPkgConfig = `pkg-config`
func defaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "gcc"
	}
	return "arm-linux-androideabi-gcc"
}
func defaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "g++"
	}
	return "arm-linux-androideabi-g++"
}
