// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /home/mythical/Downloads/go/src/cmd/compile/internal/gc/race.go

//line /home/mythical/Downloads/go/src/cmd/compile/internal/gc/race.go:1
// Copyright 2017 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build race

package gc

const raceEnabled = true
