// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /home/mythical/Downloads/go/src/cmd/cgo/zdefaultcc.go

//line /home/mythical/Downloads/go/src/cmd/cgo/zdefaultcc.go:1
// Code generated by go tool dist; DO NOT EDIT.

package main

const defaultPkgConfig = `pkg-config`
func defaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "gcc"
	}
	return "arm-linux-androideabi-gcc"
}
func defaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	case "linux/amd64":
		return "g++"
	}
	return "arm-linux-androideabi-g++"
}
